### ISSUE TITLE
Unable to save reworked Annotation 

### ISSUE THREAD

**Issue by SaibotMagd** [sanderslab/magellanmapper#11]
Hi, after basic protocol 4 step 4, label editing the save function doesn't work:
could this be an issue regarding the filename to be saved to? like [https://itk.org/pipermail/insight-users/2015-May/052068.html](url) mentioned? 

```

root - INFO - name: dorsal pallium/isocortex False
root - INFO - updating specified color to 
root - INFO - updating specified color to None
root - ERROR - Traceback (most recent call last):
root - ERROR -   File "/home/nrd/anaconda3/envs/mag/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 196, in process
    func(*args, **kwargs)
root - ERROR -   File "/home/nrd/anaconda3/envs/mag/lib/python3.6/site-packages/matplotlib/widgets.py", line 211, in _release
    func(event)
root - ERROR -   File "/home/nrd/magellanmapper/magmap/gui/atlas_editor.py", line 377, in save_atlas
    overwrite=True)
root - ERROR -   File "/home/nrd/magellanmapper/magmap/io/sitk_io.py", line 355, in write_registered_image
    sitk.WriteImage(reg_img, reg_img_path, False)
root - ERROR -   File "/home/nrd/anaconda3/envs/mag/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 8215, in WriteImage
    return _SimpleITK.WriteImage(*args)
root - ERROR - RuntimeError: Exception thrown in SimpleITK WriteImage: /mnt/e/src/SimpleElastix/Code/IO/src/sitkImageFileWriter.cxx:175:
sitk::ERROR: Unable to determine ImageIO writer for "/home/nrd/magellanmapper/examples/ADMBA-E18pt5/annotation."
root - INFO - name: dorsal pallium/isocortex False

```

**Comment by yoda-vid** [comment]
Thanks for another find, @SaibotMagd ! I tracked this down to an error because the filename extension gets stripped when loading the labels image through the GUI, making SimpleITK unable to figure out the file format to save. Loading the image through the command-line bypasses this stripping, so the error doesn't appear there.

I pushed another fix in PR #13 . The filename extensions are now saved with these registered image names in the GUI, which actually simplifies finding these images and fixes the save issue. It's available on Git by:
`git fetch; git checkout fix_save_atlas_loaded_from_gui`

Thanks again and let me know how it works for you or if you encounter any other issues!

**Comment by SaibotMagd** [comment]
I tried this but it doesn't work. Because the other fix worked (and I manually checked if the changes are written locally), it seems not to a working solution. Error message is identical.

I will try to replicate the error using nifti files because maybe the issue is because of the dual file situation combining the MHD and RAW file.

**Comment by yoda-vid** [comment]
Thanks for letting me know. Just to double-check, did you run `git fetch; git checkout fix_save_atlas_loaded_from_gui`? This fix is actually on a different branch from the other issue. Does the "Labels" dropdown box show file extensions, like "annotion.mhd"? They should be present now to tell SimpleITK the file format to write.

![image](https://user-images.githubusercontent.com/1258953/114848378-383bae00-9e11-11eb-9e8b-0c126be794b2.png)

And the command-line output then shows, `wrote <path>/ADMBA-E18pt5/annotation.mhd with current registered image`. Let me know if this doesn't work for you though. Are you loading the images through the GUI?

**Comment by SaibotMagd** [comment]
> 
> 
> Thanks for letting me know. Just to double-check, did you run `git fetch; git checkout fix_save_atlas_loaded_from_gui`? This fix is actually on a different branch from the other issue. Does the "Labels" dropdown box show file extensions, like "annotion.mhd"? They should be present now to tell SimpleITK the file format to write.
> 

Very important that you checked this source of an error on my side. I'm not really familiar with git so I missed that you fixed both issues in 2 separate branches. So after switching the branch it works! Yes it shows the file-ending in the gui right now.

You maybe think about an undo function in the future. I'm fine with overwriting the file but this could lead to some usability issues.

**Comment by yoda-vid** [comment]
Great, glad we got it all sorted out! Thanks again for pointing out these issues and helping me to fix them.

The undo feature is a great idea...I'll add an issue to keep a reminder of it.
