### ISSUE TITLE
build a Documentation 

### ISSUE THREAD

**Issue by SaibotMagd** [sanderslab/magellanmapper#3]
Hello,

I try to use the magellanmapper to perform a 2D to 3D atlas transformation like you did in "Constructing and Optimizing 3D Atlases From 2D Data With Application to the Developing Mouse Brain". Right now I've got a couple of annotated plates as SVG Annotations on Nissl Plates. I'm going to stitch them to separate tiff-volumn files and I thought the "between-plate" interpolate smoothing could be done using  magellanmapper.

I started to build the sphinx documentation but something went wrong. 
![image](https://user-images.githubusercontent.com/67700096/103282102-ed6a6780-49d4-11eb-91db-ddcc3569f080.png)
. It seems like I have to set some directories beforehand. I already set "`sys.path.append('~/Atlas_project/magellanmapper')`" in conf.py

Or Is there already a doc I couldn't find?

**Comment by yoda-vid** [comment]
Thanks for pointing this out. The `.rst` files need to be generated beforehand using `sphinx-apistart` before the `make html` command. There's a Bash convenience script for these commands in the `bin` folder, which you can access by:

```
bin/build_docs.sh -a
```

to both build the `.rst` files and the HTML documentation. Afterward, you can run `bin/build_docs.sh` alone to rebuild the HTML docs. There will still be many warnings, but the HTML output folder should contain the API docs.

For the between-plate interpolation, are you referring to the edge interpolation tool? There isn't (yet) any docs on using the interpolation tools except for the `InterpolatePlanes` class [API itself](https://github.com/sanderslab/magellanmapper/blob/b3c5e36413dfd66a5a75c7b5bef19884bb2fd0fd/magmap/gui/atlas_editor.py#L504). The tool can be accessed through the GUI though as the "Fill Label" button in the lower left area of the Atlas Editor. It currently works for a single edited label at a time. The label is specified by editing it in one plane again in another plane. Pressing the fill button then interpolates between these two planes.  If you have access to [Current Protocols](https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/cpns.104), we describe using the interpolation tool in Basic Protocol 4 and Fig 6.

If you're referring to the 3D smoothing functions (the "edge-aware" smoothing and morphological smoothing steps), their usage is described in Basic Protocol 5. We also plan to add more docs to this repo to describe how to use them.

We will need to add more docs about building docs too; thanks again!

**Comment by SaibotMagd** [comment]
> There will still be many warnings, but the HTML output folder should contain the API docs.
Thanks, It works and I've got something to work on.

> For the between-plate interpolation, are you referring to the edge interpolation tool? 
> If you're referring to the 3D smoothing functions (the "edge-aware" smoothing and morphological smoothing steps)
I have no idea. Like I said: my goal is to create a 3D Atlas out of 2D annotations on 2D Plates only exist in a printed paper. I first transfered the prints to vector-graphic slices using unique color codes for each marked region. Next step will be a registration of the nissl plates (the 2D annotations were created using the information of myelin and nissl staining slices) on LSFM slices. To do this I think I need a validation statistic to optimize the precision of the registration.

In the end I will have a 3D whole brain LSFM autofluorescence image and a matching segmentation overlay for some parts of the LSFM image. So the gaps between the segmentations should be interpolated.  

So I think I should do it both ways? I really have no clue how to fullfill the task, I just thought your pipeline could be helpful.

**Comment by yoda-vid** [comment]
Thanks, I think I understand your scenario better now. The tool might help with at least some of the steps. If I understand correctly, you would have annotated planes registered to an LSFM image volume, with annotating slices located at approximately regular intervals and larger unannotated gaps between them to fill in. The between-plate interpolation tool is designed to interpolate edges between a single label in two separate planes, typically edited manually in the GUI, so I have not tested it yet for interpolating all labels between two planes. But it may work, eg iterating through all labels (see [this function](https://github.com/sanderslab/magellanmapper/blob/b3c5e36413dfd66a5a75c7b5bef19884bb2fd0fd/magmap/cv/cv_nd.py#L725)).

You could also potentially use a standard interpolation on the full volume by collapsing the planes to remove their gaps and using a nearest neighbor or other interpolator to resize them back to the original volume. Then to fit interpolated labels to the LSFM image, you could use the tool's label erosion followed by the "edge-aware" watershed to remold labels based on your LSFM image. Once complete, you could use the edge interpolator to manually refine specific labels that need further tweaking if necessary.

So the steps could roughly be:
1. Register annotated Nissl plates to LSFM (eg some tools [here](https://forum.image.sc/t/development-of-python-based-2d-section-3d-atlas-registration-tool/39719/20))
2. `interpolate_label_between_planes` for each label in each pair of planes, or use something like Scikit-image's `trasnform.resize` function (with an order of 0 to preserve label identities) for the whole annotated volume
3. Make an anatomical edge image from the LSFM image: `./run.py --img <imported-lsfm-img-path> --register make_edge_images`
4. Erode and regrow labels based on the anatomical map: `./run.py --img <imported-lsfm-img-path> --register merge_atlas_segs`

The last steps are described in more detail in Basic Protocol 5. Let me know if this helps.

**Comment by SaibotMagd** [comment]
> If I understand correctly, you would have annotated planes registered to an LSFM image volume, with annotating slices located at approximately regular intervals and larger unannotated gaps between them to fill in. 

Yes, and the intervals are nearly identical. I'm not really familiar with interpolation in images but I think the rules should be similar to data imputation. So I estimate the maximum proportion of "gaps" to be 20-30% for a valuable result. So I down-sample both the LSFM image and the nissl slices to fit this proportion. Without the downsampling the proportion of annotations is under 5% so 95% are gaps.

>     1. Register annotated Nissl plates to LSFM (eg some tools [here](https://forum.image.sc/t/development-of-python-based-2d-section-3d-atlas-registration-tool/39719/20))

Most of these tools do a 2D Slice to 3D volumne registration. I see no advantage in doing it this way. I tried rigid, affine, spline registrations using elastix for 2D nissl on 2D LSFM slices. The result doesn't seem so bad. But I think Fürth Approach (Wholebrain package) could be even better because it uses vector graphics. 

Thank you!

**Comment by yoda-vid** [comment]
Yes, minimizing the gaps will be helpful for the interpolation, especially for complex or heterogeneous structures. The "edge-aware" step in this tool can work around this issue to some extent by remolding the labels based on the Nissl image after interpolation to reduce artifacts.

If your annotated plates are at equal intervals and aligned with one another, you could potentially stack them up without gaps, resize/interpolate the stack to the dimensions of the LSFM image, and then do a 3D-to-3D registration to the LSFM brain. The "edge-aware" remolding step could then be done based on the Nissl or LSFM image.
