### ISSUE TITLE
Windows display issues

### ISSUE THREAD

**Issue by kaparna126** [sanderslab/magellanmapper#38]
When magellanmapper is opened via the source code version on Windows, the display is really zoomed in. Display settings need to be changed from 150% zoom to 100% zoom to see the whole window. This problem seems to be absent with the installer version of the software.

**Comment by yoda-vid** [comment]
Thanks for reporting, @kaparna126! This probably has to do with the HiDPI settings for PyQt here:
 https://github.com/sanderslab/magellanmapper/blob/a0ab61c1805fcfc91c670f62b95262bebbb00c1e/magmap/gui/visualizer.py#L28-L37

Will need to troubleshoot the window resolution in various Windows display scaling scenarios. Thanks for your workaround in the meantime.

**Comment by yoda-vid** [comment]
I added a PR (#62) that sets a smaller default window width and allows the window height to be resized by keeping the window top bar in the screen on Windows. This should avoid having to adjust the Windows display settings to resize/reposition the window.
