### ISSUE TITLE
Software crashes before opening with installer version on Mac 13.6

### ISSUE THREAD

**Issue by kaparna126** [sanderslab/magellanmapper#48]
The installer version of Magellan Mapper loads, but then crashes before opening every time on my Mac (version 13.6).

**Comment by yoda-vid** [comment]
Thanks for finding this, @kaparna126! Looks like it's from being built on Mac 10.15 (see PyInstaller [notes](https://pyinstaller.readthedocs.io/en/stable/usage.html#making-mac-os-x-apps-forward-compatible)). I retested it on 10.14, which works fine, but 10.13 must have some incompatibilities. I'll need to rebuild on 10.13.

**Comment by yoda-vid** [comment]
Thanks again for reporting this! Now that MacOS 12 is out, and we aren't able to test on 10.13 regularly, I'll need to stick with our current installer builds that work on 10.14+.

The [installation from source](https://github.com/sanderslab/magellanmapper#install-from-source) pathway should still work for 10.13. If there is still need for installer packages for 10.13, please chime in!
